/**
 * Build-time config injection for Audio Chat surface.
 *
 * Reads AUDIO_GATEWAY_URL from the environment and writes it to config.js
 * so the static app can use a default gateway in production while still
 * allowing ?gateway=... override for local testing.
 */

const fs = require('fs');
const path = require('path');

const gatewayUrl = (process.env.AUDIO_GATEWAY_URL || '').replace(/\/$/, '');
const chatApiUrl = (process.env.AUDIO_CHAT_API_URL || '').replace(/\/$/, '');

const configPath = path.join(__dirname, 'config.js');
const content = `// Auto-generated by build.js. Do not edit manually.
window.AUDIO_GATEWAY_URL = ${gatewayUrl ? JSON.stringify(gatewayUrl) : 'null'};
window.AUDIO_CHAT_API_URL = ${chatApiUrl ? JSON.stringify(chatApiUrl) : 'null'};
`;

fs.writeFileSync(configPath, content, 'utf8');
console.log(`Wrote config.js with gateway: ${gatewayUrl || '(none)'}, chat API: ${chatApiUrl || '(none)'}`);
