entraOidcTenantId = "2f013f08-f893-436f-becc-9f82d02ca76d"
entraOidcTenantId = ${?ENTRA_OIDC_TENANT_ID}

oidcClients = [
  {
    id = "entra-dss-issuer"
    url = "https://login.microsoftonline.com/" ${entraOidcTenantId} "/v2.0"
    clientId = "${ENTRA_OIDC_CLIENT_ID}"
    clientSecret = "${ENTRA_OIDC_CLIENT_SECRET}"
    scope = "openid profile email"
  }
]
