#!/usr/bin/env python3
"""Build-time generator for backend/kernel/constants.py.

Reads the Kernel Semantic Registry (KSR) and emits a frozen public constant
module that contains only strict engineering terminology. Esoteric/loaded
terms live only in the encrypted KSR and steward documentation.

Usage:
    # From plaintext YAML (development / steward build):
    python scripts/generate_kernel_constants.py

    # From encrypted envelope (CI, when only semantic_registry.enc is present):
    DSS_KSR_PASSWORD=<secret> python scripts/generate_kernel_constants.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent))

import yaml  # noqa: E402

from backend.kernel.ksr_crypto import load_ksr_yaml  # noqa: E402


TEMPLATE = '''# Generated by scripts/generate_kernel_constants.py
# DO NOT EDIT MANUALLY.
# Source: backend/kernel/semantic_registry.yaml (private)
# This file contains only strict engineering terminology.

from __future__ import annotations

from enum import IntEnum
from typing import Any, Final, FrozenSet, Mapping, Tuple


class ImmutableKernelError(RuntimeError):
    """Raised when runtime code attempts to mutate a frozen kernel constant."""

    code = "IMMUTABLE_KERNEL"


class _ImmutableMapping(Mapping):
    """Recursive, runtime-immutable mapping view used to freeze kernel registries."""

    __slots__ = ("_data",)

    def __init__(self, data: Mapping[Any, Any]) -> None:
        self._data = {{k: _freeze(v) for k, v in data.items()}}

    def __getitem__(self, key: Any) -> Any:
        return self._data[key]

    def __iter__(self):
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    def __repr__(self) -> str:
        return f"_ImmutableMapping({{self._data!r}})"

    def __setitem__(self, key: Any, value: Any) -> None:
        raise ImmutableKernelError(
            f"IMMUTABLE_KERNEL: cannot modify {{key!r}} in frozen kernel mapping"
        )

    def __delitem__(self, key: Any) -> None:
        raise ImmutableKernelError(
            f"IMMUTABLE_KERNEL: cannot delete {{key!r}} from frozen kernel mapping"
        )

    def update(self, *args, **kwargs) -> None:
        raise ImmutableKernelError("IMMUTABLE_KERNEL: cannot update frozen kernel mapping")

    def pop(self, key: Any, *args) -> Any:
        raise ImmutableKernelError(
            f"IMMUTABLE_KERNEL: cannot pop {{key!r}} from frozen kernel mapping"
        )

    def popitem(self) -> tuple[Any, Any]:
        raise ImmutableKernelError("IMMUTABLE_KERNEL: cannot pop item from frozen kernel mapping")

    def clear(self) -> None:
        raise ImmutableKernelError("IMMUTABLE_KERNEL: cannot clear frozen kernel mapping")

    def setdefault(self, key: Any, default: Any = None) -> Any:
        raise ImmutableKernelError(
            f"IMMUTABLE_KERNEL: cannot setdefault {{key!r}} in frozen kernel mapping"
        )


def _freeze(value: Any) -> Any:
    """Recursively freeze mutable kernel values at import time."""
    if isinstance(value, dict):
        return _ImmutableMapping(value)
    if isinstance(value, list):
        return tuple(_freeze(v) for v in value)
    return value


# KSR metadata ----------------------------------------------------------------
KSR_VERSION: Final[str] = {ksr_version}
REFERENCE_DOCUMENTS: Final[Mapping[str, Mapping[str, str]]] = {reference_documents}

# KSR scope statement ---------------------------------------------------------
KSR_SCOPE_STATEMENT: Final[str] = {ksr_scope_statement}

# Confidence taxonomy ---------------------------------------------------------
CONFIDENCE_TAXONOMY: Final[Mapping[str, str]] = {confidence_taxonomy}

# Relation types --------------------------------------------------------------
RELATION_TYPES: Final[Tuple[str, ...]] = {relation_types}


class DigitSymbol(IntEnum):
    """Symbolic digit alphabet for the kernel circulation trace."""

{digit_symbols}


# Kernel node identifiers -----------------------------------------------------
KERNEL_NODE_NAMES: Final[Tuple[str, ...]] = {node_names}
KERNEL_NODE_EQ_NAMES: Final[Tuple[str, ...]] = {eq_names}

# Prime topology --------------------------------------------------------------
MEDIATOR_TWIN_PRIMES: Final[Tuple[int, int]] = {mediator_twin_primes}
CONSTRAINT_PRIME: Final[int] = {constraint_prime}
RELAXATION_PRIME: Final[int] = {relaxation_prime}
BODY_PRIMES_START: Final[int] = {body_primes_start}

S1_PRIMES: Final[Tuple[int, ...]] = {s1_primes}
S2_PRIMES: Final[Tuple[int, ...]] = {s2_primes}
MEDIATOR_PRIMES: Final[Tuple[int, ...]] = {mediator_primes}
ALL_KERNEL_PRIMES: Final[Tuple[int, ...]] = {all_kernel_primes}

# Tier roles ------------------------------------------------------------------
SOURCE_TIERS: Final[FrozenSet[str]] = frozenset({source_tiers})
TARGET_TIERS: Final[FrozenSet[str]] = frozenset({target_tiers})
MEDIATOR_TIERS: Final[FrozenSet[str]] = frozenset({mediator_tiers})

# Node -> structural metadata -------------------------------------------------
NODE_TO_DIGIT_SYMBOL: Final[Mapping[str, DigitSymbol]] = {node_to_digit}
NODE_TO_METRIC_PRIME: Final[Mapping[str, int]] = {node_to_prime}
NODE_TO_TETRAHEDRON: Final[Mapping[str, str]] = {node_to_tet}
DUAL_COMPLEMENTS: Final[Mapping[str, str]] = {dual_complements}

# Engineering dimension map (prime -> operational dimension) ------------------
PRIME_TO_DIMENSION: Final[Mapping[int, str]] = {prime_to_dimension}

# Checksum invariant ----------------------------------------------------------
CHECKSUM_336: Final[int] = {checksum_336}

# Quaternary gate registry (v1.3-alpha) ---------------------------------------
QUATERNARY_GATE_REGISTRY_VERSION: Final[str] = {quaternary_version}
QUATERNARY_ENCODING: Final[str] = {quaternary_encoding}
QUATERNARY_SEMANTIC_CHECKSUM_BASE: Final[int] = {quaternary_checksum_base}
QUATERNARY_SEMANTIC_CHECKSUM_FORMULA: Final[str] = {quaternary_checksum_formula}
QUATERNARY_SEMANTIC_CHECKSUM_NON_COMPENSATORY: Final[bool] = {quaternary_checksum_non_compensatory}

QUATERNARY_GATE_KEYS: Final[Tuple[str, ...]] = {quaternary_gate_keys}
QUATERNARY_GATE_TO_EQUATION: Final[Mapping[str, str]] = {quaternary_gate_to_equation}
QUATERNARY_GATE_TO_PRIME: Final[Mapping[str, int]] = {quaternary_gate_to_prime}
QUATERNARY_GATE_TO_DIMENSION: Final[Mapping[str, str]] = {quaternary_gate_to_dimension}
QUATERNARY_LEVEL_KEYS: Final[Tuple[str, ...]] = {quaternary_level_keys}
QUATERNARY_LEVEL_VALUES: Final[Tuple[float, ...]] = {quaternary_level_values}
QUATERNARY_GATES: Final[Mapping[str, Mapping[str, Any]]] = {quaternary_gates}

QUATERNARY_LAYER_ORDER: Final[Tuple[str, ...]] = {quaternary_layer_order}
QUATERNARY_LAYER_TOPOLOGY: Final[Mapping[str, Mapping[str, Any]]] = {quaternary_layer_topology}

LAYER_SAND: Final[str] = "SAND"
LAYER_SILT: Final[str] = "SILT"
LAYER_LOAM: Final[str] = "LOAM"
LAYER_CLAY: Final[str] = "CLAY"

ELEVATION_PROOF_REQUIRED_PROOFS: Final[Tuple[str, ...]] = {elevation_proofs_required}
QUATERNARY_NON_COMPENSATORY_RULES: Final[Tuple[str, ...]] = {quaternary_non_compensatory_rules}

# Lattice registry (neutral engineering view) ---------------------------------
LATTICE_REGISTRY_VERSION: Final[str] = {lattice_version}
LATTICE_CUBE_ID: Final[str] = {lattice_cube_id}
LATTICE_TYPE: Final[str] = {lattice_type}
LATTICE_TOTAL_NODES: Final[int] = {lattice_total_nodes}
LATTICE_CENTROID_COORDINATE: Final[str] = {lattice_centroid_coordinate}
LATTICE_RESET_COORDINATE: Final[str] = {lattice_reset_coordinate}
LATTICE_CORNER_MAP: Final[Mapping[str, Mapping[str, Any]]] = {lattice_corner_map}
LATTICE_BRIDGE_EDGES: Final[Tuple[Mapping[str, Any], ...]] = {lattice_bridge_edges}
LATTICE_FACE_CENTERS: Final[Tuple[Mapping[str, Any], ...]] = {lattice_face_centers}
LATTICE_TRAVERSAL_SEQUENCE: Final[Tuple[str, ...]] = {lattice_traversal_sequence}
LATTICE_FLOW_RULES: Final[Tuple[str, ...]] = {lattice_flow_rules}
CHECKSUM_336_LATTICE_RULES: Final[Mapping[str, Any]] = {checksum_336_lattice_rules}

# Commandment patch registry (engineering replacements only) ------------------
PATCH_REGISTRY_VERSION: Final[str] = {patch_version}
PATCH_IDS: Final[Tuple[str, ...]] = {patch_ids}
PATCH_REGISTRY: Final[Mapping[str, Mapping[str, Any]]] = {patch_registry}
PATCH_E6_PATCH_BITS: Final[Tuple[int, int]] = {patch_e6_patch_bits}
PATCH_E6_CHECKSUM_BITS: Final[Tuple[int, int]] = {patch_e6_checksum_bits}
PATCH_E6_RESERVED_BITS: Final[Tuple[int, int]] = {patch_e6_reserved_bits}

# Value-node registry (diagnostic balance layer) ------------------------------
VALUE_NODE_REGISTRY_VERSION: Final[str] = {value_node_version}
VALUE_NODE_LABELS: Final[Tuple[str, ...]] = {value_node_labels}
VALUE_NODE_DIMENSIONS: Final[Mapping[str, str]] = {value_node_dimensions}
VALUE_NODE_PRIME_AFFINITIES: Final[Mapping[str, int]] = {value_node_prime_affinities}
VALUE_NODE_BALANCE_RULES: Final[Mapping[str, Any]] = {value_node_balance_rules}

# Personality-type overlay (optional user-profile prior) ----------------------
PERSONALITY_TYPE_OVERLAY_VERSION: Final[str] = {personality_overlay_version}
PERSONALITY_TYPE_OVERLAY_OPTIONAL: Final[bool] = {personality_overlay_optional}
PERSONALITY_TYPE_OVERLAY_AUTHORITY: Final[str] = {personality_overlay_authority}
COGNITIVE_PREFERENCE_AXES: Final[Mapping[str, Mapping[str, Any]]] = {cognitive_axes}
MOTIVATION_STYLE_PROFILES: Final[Mapping[str, Mapping[str, Any]]] = {motivation_profiles}
PROFILE_CORRELATION_TABLE: Final[Mapping[str, Mapping[str, Any]]] = {profile_correlation_table}


# HENGE-011: freeze the kernel registries that must never mutate at runtime ----
QUATERNARY_GATE_TO_PRIME = _freeze(QUATERNARY_GATE_TO_PRIME)
QUATERNARY_GATES = _freeze(QUATERNARY_GATES)
'''


def _load_ksr(repo_root: Path) -> dict[str, Any]:
    yaml_path = repo_root / "backend" / "kernel" / "semantic_registry.yaml"
    if yaml_path.exists():
        return yaml.safe_load(yaml_path.read_text())

    password = os.getenv("DSS_KSR_PASSWORD")
    if not password:
        raise RuntimeError(
            "No plaintext KSR found and DSS_KSR_PASSWORD is not set. "
            "Cannot generate constants from encrypted envelope."
        )
    return load_ksr_yaml(password)


def _indent(lines: str, width: int = 4) -> str:
    pad = " " * width
    return "\n".join(pad + line for line in lines.splitlines())


def _dict_repr(mapping: dict[Any, Any]) -> str:
    items = ",\n".join(f"    {k!r}: {v!r}" for k, v in mapping.items())
    return "{\n" + items + ",\n}"


def _enum_mapping_repr(mapping: dict[str, str]) -> str:
    """Render a mapping whose values are enum member references (unquoted)."""
    items = ",\n".join(f"    {k!r}: {v}" for k, v in mapping.items())
    return "{\n" + items + ",\n}"


def generate(repo_root: Path) -> str:
    ksr = _load_ksr(repo_root)

    ksr_version = ksr["ksr_version"]
    reference_documents = {
        name: {"path": info["path"], "sha256": info["sha256"]}
        for name, info in ksr.get("reference_documents", {}).items()
    }

    ksr_scope_statement = ksr.get("ksr_scope_statement", "")
    confidence_taxonomy = ksr.get("confidence_taxonomy", {})
    relation_types = tuple(ksr.get("relation_types", []))

    digit_registry = ksr["digit_registry"]
    prime_registry = ksr["prime_registry"]
    prime_groups = ksr["prime_groups"]
    flow_topology = ksr["flow_topology"]
    checksum = ksr["checksum_invariant"]

    # Build DigitSymbol enum body.
    digit_lines = []
    for key, meta in digit_registry.items():
        if key == "INF":
            continue
        symbol = meta["symbol"]
        value = meta["value"]
        digit_lines.append(f"{symbol} = {value}")
    digit_lines.append("INF = 10")
    digit_symbols = _indent("\n".join(digit_lines), width=4)

    # Node metadata.
    eq_names = [k for k in digit_registry if k.startswith("Eq")]
    node_names = eq_names + ["INF"]
    node_to_digit = {name: f"DigitSymbol.{digit_registry[name]['symbol']}" for name in eq_names}
    node_to_digit["INF"] = "DigitSymbol.INF"
    node_to_prime = flow_topology["metric_prime_map"]

    def _tet(name: str) -> str:
        if name in flow_topology["tetrahedrons"]["C"]:
            return "C"
        if name in flow_topology["tetrahedrons"]["S1"]:
            return "S1"
        if name in flow_topology["tetrahedrons"]["S2"]:
            return "S2"
        return "boundary"

    node_to_tet = {name: _tet(name) for name in node_names}
    dual_complements = flow_topology["dual_complements"]

    # Prime groupings.
    s1_primes = tuple(prime_groups["S1_PRIMES"])
    s2_primes = tuple(prime_groups["S2_PRIMES"])
    mediator_primes = tuple(prime_groups["MEDIATOR_PRIMES"])
    all_kernel_primes = tuple(sorted(
        set(s1_primes) | set(s2_primes) | set(mediator_primes)
    ))
    mediator_twin_primes = tuple(mediator_primes)
    constraint_prime, relaxation_prime = mediator_primes
    body_primes_start = prime_groups["BODY_PRIMES_START"]

    source_tiers = ["S"]
    target_tiers = ["A", "B"]
    mediator_tiers = ["C"]

    prime_to_dimension = {
        int(p): meta["engineering_dimension"]
        for p, meta in prime_registry.items()
    }

    checksum_336 = checksum["value"]

    # Quaternary gate registry -------------------------------------------------
    qgr = ksr["quaternary_gate_registry"]
    quaternary_version = qgr["version"]
    quaternary_encoding = qgr["encoding"]
    q_checksum = qgr["semantic_checksum"]
    quaternary_checksum_base = q_checksum["base"]
    quaternary_checksum_formula = q_checksum["formula"]
    quaternary_checksum_non_compensatory = bool(q_checksum["non_compensatory"])

    quaternary_gate_keys = tuple(qgr["gates"].keys())
    quaternary_gate_to_equation = {
        key: meta["equation_key"] for key, meta in qgr["gates"].items()
    }
    quaternary_gate_to_prime = {
        key: meta["prime"] for key, meta in qgr["gates"].items()
    }
    quaternary_gate_to_dimension = {
        key: meta["dimension"] for key, meta in qgr["gates"].items()
    }

    quaternary_level_keys = ("level_0", "level_1", "level_2", "level_3")
    quaternary_level_values = (0.0, 0.333, 0.666, 1.0)

    quaternary_gates = {}
    for key, meta in qgr["gates"].items():
        levels = {}
        for level_key, level_meta in meta["levels"].items():
            levels[level_key] = {
                "v_min": level_meta["v_min"],
                "v_max": level_meta["v_max"],
                "value": level_meta["value"],
                "layer": level_meta["layer"],
                "persistence": level_meta["persistence"],
            }
            if "action" in level_meta:
                levels[level_key]["action"] = level_meta["action"]
            if "retention_blocks" in level_meta:
                levels[level_key]["retention_blocks"] = level_meta["retention_blocks"]
        quaternary_gates[key] = {
            "equation_key": meta["equation_key"],
            "prime": meta["prime"],
            "dimension": meta["dimension"],
            "levels": levels,
        }

    quaternary_layer_order = tuple(
        layer.upper() for layer in qgr["layer_topology"].keys()
    )
    quaternary_layer_topology = {}
    for layer_key, layer_meta in qgr["layer_topology"].items():
        quaternary_layer_topology[layer_key.upper()] = {
            "position": layer_meta["position"],
            "permeability": layer_meta["permeability"],
            "function": layer_meta["function"],
        }
        if "decay_function" in layer_meta:
            quaternary_layer_topology[layer_key.upper()]["decay_function"] = layer_meta["decay_function"]

    elevation_proofs_required = tuple(qgr["elevation_proofs_required"])
    quaternary_non_compensatory_rules = tuple(qgr["non_compensatory_rules"])

    # Lattice registry ---------------------------------------------------------
    lattice = ksr["lattice_registry"]
    lattice_version = lattice["version"]
    lattice_cube_id = lattice["cube_id"]
    lattice_type = lattice["lattice_type"]
    lattice_total_nodes = lattice["total_nodes"]
    lattice_centroid_coordinate = lattice["centroid_coordinate"]
    lattice_reset_coordinate = lattice["reset_coordinate"]

    lattice_corner_map = {
        coord: {
            "kernel": meta["kernel"],
            "eq_node": meta["eq_node"],
            "structural_prime": meta["structural_prime"],
            "role": meta["role"],
        }
        for coord, meta in lattice["corner_map"].items()
    }

    lattice_bridge_edges = tuple(
        {
            "from": edge["from"],
            "to": edge["to"],
            "coordinate": edge["coordinate"],
            "axis": edge["axis"],
            "dual_pair": edge["dual_pair"],
            "day": edge["day"],
        }
        for edge in lattice["bridge_edges"]
    )

    lattice_face_centers = tuple(
        {
            "coordinate": face["coordinate"],
            "cube_face": face["cube_face"],
            "prime": face["prime"],
        }
        for face in lattice["face_centers"]
    )

    lattice_traversal_sequence = tuple(
        step["coordinate"] for step in lattice["traversal_sequence"]
    )
    lattice_flow_rules = tuple(lattice["flow_rules"])

    # Emit only the engineering fields for the checksum-336 lattice rules;
    # steward-only metadata (Hebrew letters, semantic descriptions) stays in the
    # encrypted KSR.
    raw_checksum_rules = lattice["checksum_336"]
    checksum_336_lattice_rules = {
        "value": raw_checksum_rules["value"],
        "formula": raw_checksum_rules.get("formula", ""),
        "required_dimensions": [
            {
                "prime": spec["prime"],
                "min_valuation": spec.get("min_valuation", spec.get("valuation", 0)),
                "pair": spec["pair"],
            }
            for spec in raw_checksum_rules.get("required_dimensions", [])
        ],
        "dual_sync_tolerance": raw_checksum_rules.get("dual_sync_tolerance", 1),
        "centroid_active": list(raw_checksum_rules.get("centroid_active", [137, 139])),
    }

    # Commandment patch registry -----------------------------------------------
    patch_reg = ksr["commandment_patch_registry"]
    patch_version = patch_reg["version"]
    patch_ids = tuple(sorted(patch_reg["patches"].keys()))
    patch_registry = {
        pid: {
            "engineering_replacement": meta["engineering_replacement"],
            "kernel_node": meta["kernel_node"],
            "structural_prime": meta["structural_prime"],
            "failure_mode": meta["failure_mode"],
            "hard_gate": meta["hard_gate"],
            "enforcement": meta["enforcement"],
            "category": meta["category"],
            "e6_bit_index": meta["e6_bit_index"],
        }
        for pid, meta in patch_reg["patches"].items()
    }
    patch_e6_patch_bits = tuple(patch_reg["e6_header_layout"]["patch_bits"])
    patch_e6_checksum_bits = tuple(patch_reg["e6_header_layout"]["checksum_bits"])
    patch_e6_reserved_bits = tuple(patch_reg["e6_header_layout"]["reserved_bits"])

    # Value-node registry ------------------------------------------------------
    value_node = ksr["value_node_registry"]
    value_node_version = value_node["version"]
    value_node_labels = tuple(value_node["nodes"].keys())
    value_node_dimensions = {
        label: meta["ksr_dimension"] for label, meta in value_node["nodes"].items()
    }
    value_node_prime_affinities = {
        label: meta["prime_affinity"] for label, meta in value_node["nodes"].items()
    }
    value_node_balance_rules = value_node["balance_rules"]

    # Personality-type overlay -------------------------------------------------
    personality_overlay = ksr.get("personality_type_overlay", {})
    personality_overlay_version = personality_overlay.get("version", "1.0")
    personality_overlay_optional = bool(personality_overlay.get("optional", True))
    personality_overlay_authority = personality_overlay.get("authority", "unknown")

    cognitive_axes = {}
    for axis_name, axis_meta in personality_overlay.get("cognitive_preference_axes", {}).items():
        cognitive_axes[axis_name] = {
            "pole_a": {
                "label": axis_meta["pole_a"]["label"],
                "value_node_bias": dict(axis_meta["pole_a"]["value_node_bias"]),
            },
            "pole_b": {
                "label": axis_meta["pole_b"]["label"],
                "value_node_bias": dict(axis_meta["pole_b"]["value_node_bias"]),
            },
        }

    motivation_profiles = {
        profile: {
            "value_node_weights": dict(meta["value_node_weights"]),
        }
        for profile, meta in personality_overlay.get("motivation_style_profiles", {}).items()
    }

    profile_correlation_table = {
        profile: {
            "top_styles": [
                {"style": entry["style"], "weight": entry["weight"]}
                for entry in meta.get("top_styles", [])
            ],
        }
        for profile, meta in personality_overlay.get("profile_correlation_table", {}).items()
    }

    return TEMPLATE.format(
        ksr_version=repr(ksr_version),
        reference_documents=repr(reference_documents),
        ksr_scope_statement=repr(ksr_scope_statement),
        confidence_taxonomy=repr(confidence_taxonomy),
        relation_types=repr(relation_types),
        digit_symbols=digit_symbols,
        node_names=repr(tuple(node_names)),
        eq_names=repr(tuple(eq_names)),
        mediator_twin_primes=repr(mediator_twin_primes),
        constraint_prime=constraint_prime,
        relaxation_prime=relaxation_prime,
        body_primes_start=body_primes_start,
        s1_primes=repr(s1_primes),
        s2_primes=repr(s2_primes),
        mediator_primes=repr(mediator_primes),
        all_kernel_primes=repr(all_kernel_primes),
        source_tiers=repr(tuple(source_tiers)),
        target_tiers=repr(tuple(target_tiers)),
        mediator_tiers=repr(tuple(mediator_tiers)),
        node_to_digit=_enum_mapping_repr(node_to_digit),
        node_to_prime=_dict_repr(node_to_prime),
        node_to_tet=_dict_repr(node_to_tet),
        dual_complements=_dict_repr(dual_complements),
        prime_to_dimension=_dict_repr(prime_to_dimension),
        checksum_336=checksum_336,
        quaternary_version=repr(quaternary_version),
        quaternary_encoding=repr(quaternary_encoding),
        quaternary_checksum_base=quaternary_checksum_base,
        quaternary_checksum_formula=repr(quaternary_checksum_formula),
        quaternary_checksum_non_compensatory=quaternary_checksum_non_compensatory,
        quaternary_gate_keys=repr(quaternary_gate_keys),
        quaternary_gate_to_equation=_dict_repr(quaternary_gate_to_equation),
        quaternary_gate_to_prime=_dict_repr(quaternary_gate_to_prime),
        quaternary_gate_to_dimension=_dict_repr(quaternary_gate_to_dimension),
        quaternary_level_keys=repr(quaternary_level_keys),
        quaternary_level_values=repr(quaternary_level_values),
        quaternary_gates=repr(quaternary_gates),
        quaternary_layer_order=repr(quaternary_layer_order),
        quaternary_layer_topology=repr(quaternary_layer_topology),
        elevation_proofs_required=repr(elevation_proofs_required),
        quaternary_non_compensatory_rules=repr(quaternary_non_compensatory_rules),
        lattice_version=repr(lattice_version),
        lattice_cube_id=repr(lattice_cube_id),
        lattice_type=repr(lattice_type),
        lattice_total_nodes=lattice_total_nodes,
        lattice_centroid_coordinate=repr(lattice_centroid_coordinate),
        lattice_reset_coordinate=repr(lattice_reset_coordinate),
        lattice_corner_map=repr(lattice_corner_map),
        lattice_bridge_edges=repr(lattice_bridge_edges),
        lattice_face_centers=repr(lattice_face_centers),
        lattice_traversal_sequence=repr(lattice_traversal_sequence),
        lattice_flow_rules=repr(lattice_flow_rules),
        checksum_336_lattice_rules=repr(checksum_336_lattice_rules),
        patch_version=repr(patch_version),
        patch_ids=repr(patch_ids),
        patch_registry=repr(patch_registry),
        patch_e6_patch_bits=repr(patch_e6_patch_bits),
        patch_e6_checksum_bits=repr(patch_e6_checksum_bits),
        patch_e6_reserved_bits=repr(patch_e6_reserved_bits),
        value_node_version=repr(value_node_version),
        value_node_labels=repr(value_node_labels),
        value_node_dimensions=_dict_repr(value_node_dimensions),
        value_node_prime_affinities=_dict_repr(value_node_prime_affinities),
        value_node_balance_rules=repr(value_node_balance_rules),
        personality_overlay_version=repr(personality_overlay_version),
        personality_overlay_optional=personality_overlay_optional,
        personality_overlay_authority=repr(personality_overlay_authority),
        cognitive_axes=repr(cognitive_axes),
        motivation_profiles=repr(motivation_profiles),
        profile_correlation_table=repr(profile_correlation_table),
    )


def main() -> int:
    repo_root = Path(__file__).parent.parent
    out_path = repo_root / "backend" / "kernel" / "constants.py"
    source = generate(repo_root)
    out_path.write_text(source)
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
